all:
	make --no-print-directory -f OVL_EVEN_PARITY
	make --no-print-directory -f OVL_WIN_CHANGE
	make --no-print-directory -f OVL_FIFO_INDEX

clean:
	  rm -fr a.out *.log *.vcd tee

help:
	make --no-print-directory -f OVL_EVEN_PARITY help
	make --no-print-directory -f OVL_WIN_CHANGE  help
	make --no-print-directory -f OVL_FIFO_INDEX  help